services:
  woodpecker:
    build: .
    image: woodpecker
    container_name : woodpecker
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TICKET_SYSTEM_TOKEN=${TICKET_SYSTEM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - TIME1=${TIME1}
      - TIME2=${TIME2}
      - URL_GET_HERO =${URL_GET_HERO}'
    restart: always
    networks:
      - n8n_mynetwork

networks:
  n8n_mynetwork:
    external: true